[package]
name = "rustnet"
version = "0.1.0"
edition = "2021"

[lib]
name = "rustnet"
path = "src/lib.rs"

[[bin]]
name = "rustnet"
path = "src/main.rs"

[dependencies]
mnist = "0.6.0"
ndarray = "0.16.1"
rand = "0.8.5"
